# Chart default values. Override by passing --set or -f to helm.

# Volumes made accessible for workers for model data or any other worker specific data.
# Mount them in a worker by adding them to workers.volumes.
modelVolumes:
#  - name: A unique volume name
#    storageCapacity: The size limit of this volume
#    hostPath: Path on the data on the kubernetes host node.
  # Piwind model data - hostPath must exist on the nodes fs
  - name: piwind-model-data-pv
    storageCapacity: 1Gi
    hostPath: /data/model-data/piwind/

workers:
  - supplierId: OasisLMF
    modelId: PiWind
    modelVersionId: "1"
    image: ${ACR}/coreoasis/model_worker
    version: dev
    imagePullPolicy: Always
    env: # Additional worker environment variables
      - name: OASIS_DEBUG
        value: "1"
      - name: OASIS_MODEL_DATA_DIRECTORY
        value: /home/worker/model
    volumes: # Volume defined in modelVolumes
      - name: piwind-model-data-pv
        mountPath: /home/worker/model
        type: model-data

registration_job:
  nodeSelector:
    oasis/node-type: platform

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: oasis/node-type
              operator: In
              values:
                - platform
# Enable when we can use worker node
#                - worker
#  podAntiAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      - labelSelector:
#          matchExpressions:
#            - key: oasis/pod-type
#              operator: In
#              values:
#                - worker
#        topologyKey: "kubernetes.io/hostname"

## Values to keep in sync with oasis-platform values ##
databases:
  broker:
    name: broker
    port: 5672
  celery_db:
    name: celery-db
    port: 5432
    type: postgres

oasisServer:
  name: oasis-server

volumes:
  sharedFs:
    name: shared-fs
## End of sync with oasis-platform values ##
