# Chart default values. Override by passing --set or -f to helm.

# Volumes made accessible for workers for model data or any other worker specific data.
# Mount them in a worker by adding them to workers.volumes.
modelVolumes:
  - name: oasis-models-azure-file
    source: azureFiles
    csi:
      driver: file.csi.azure.com
      volumeAttributes:
        secretName: oasis-storage-account
        shareName: models

workers:
  - supplierId: OasisLMF
    modelId: PiWind
    modelVersionId: "1"
    image: ${ACR}/coreoasis/model_worker
    version: dev
    imagePullPolicy: Always
    env: # Additional worker environment variables
      - name: OASIS_DEBUG
        value: "1"
      - name: OASIS_MODEL_DATA_DIRECTORY
        value: /home/worker/model
    volumes: # Volume defined in modelVolumes
      - name: oasis-models-azure-file
        type: model-data
        mountPath: /home/worker/model
        source: azureFiles

registration_job:
  nodeSelector:
    oasislmf/node-type: platform

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: oasislmf/node-type
              operator: In
              values:
                - worker
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: oasislmf/type
              operator: In
              values:
                - worker
        topologyKey: "kubernetes.io/hostname"

## Values to keep in sync with oasis-platform values ##
#databases:
#  broker:
#    name: broker
#    port: 5672
#  celery_db:
#    name: celery-db
#    port: 5432
#    type: postgres
#
#oasisServer:
#  name: oasis-server
#
#volumes:
#  host: null
#  azureFiles:
#    sharedFs:
#      csi:
#        driver: file.csi.azure.com
#        volumeAttributes:
#          secretName: oasis-storage-account
#          shareName: oasisfs
## End of sync with oasis-platform values ##
