modelVolumes:
  - name: oasis-models-azure-file
    source: azureFiles
    csi:
      driver: file.csi.azure.com
      volumeAttributes:
        secretName: oasis-storage-account
        shareName: models

# workers: - You can either add models here or to separate files in workers/, or both.

registration_job:
  nodeSelector:
    oasislmf/node-type: platform

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: oasislmf/node-type
              operator: In
              values:
                - worker
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: oasislmf/type
              operator: In
              values:
                - worker
        topologyKey: "kubernetes.io/hostname"
