

# Dependencies / sub charts settings
kube-prometheus-stack:
  prometheus-node-exporter:
    hostRootFsMount: false

  prometheus:
    prometheusSpec:
      externalUrl: 'https://${DOMAIN}/prometheus/'
      routePrefix: '/prometheus/'
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - ${DOMAIN}
      tls:
        - secretName: tls-secret
          hosts:
            - ${DOMAIN}
      paths:
        - /prometheus/

  alertmanager:
    alertmanagerSpec:
      routePrefix: /alert-manager/
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - ${DOMAIN}
      paths:
        - /alert-manager/

  grafana:
    adminPassword: password
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: true
      live:
        # https://github.com/grafana/grafana/issues/36929
        allowed_origins: "https://*"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - ${DOMAIN}
      path: /grafana/

