apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-db-init-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.secretProvider.userAssignedIdentityClientID }}
    keyvaultName: {{ .Values.azure.secretProvider.keyvaultName }}
    tenantId: {{ .Values.azure.tenantId }}
    objects:  |
      array:
{{- range .Values.azure.secretProvider.secrets }}
        - |
          objectName: {{ . }}
          objectType: secret             # object types: secret, key, or cert
{{- end }}
  secretObjects:
{{- range .Values.azure.secretProvider.secrets }}
    - data:
        - key: {{ . }}
          objectName: {{ . }}
      secretName: {{ . }}
      type: Opaque
{{- end }}
